### ISSUE TITLE
Document dependencies with links to projects

### ISSUE THREAD

**Issue by sjlongland** [kampfschlaefer/jackmix#18]
Hi,

Can we please better document the dependencies?  I thought I'd quickly throw this package on, but the installation turned into a game of whack-a-mole as each unmet dependency revealed itself.  Not fun given I had to sort out `scons`-related breakage due to the build scripts not being compatible with Python 3.

Host system is Ubuntu 20.04 AMD64.

* `iostream` header does not get located, yet I have `libstdc++-9-dev` which installs that file at `/usr/include/c++/9/iostream` -- for now I've just commented out that check, but it would seem that maybe there's an undeclared dependency somewhere?
* `lash-1` is stated as a dependency, but no link to where you get it from.

The latter one is pretty insidious.  Google is no help:
![image](https://user-images.githubusercontent.com/1710526/149262664-bbdc6fdd-2c22-4778-9df8-055f708b7676.png)

I'd like to give this project a honest try, but I suspect it's fallen into a state of bitrot now.

**Comment by nickbailey** [comment]
Lash is dead. Check out the no-lash branch. I'll merge it into the main one when the testing's finished. It also works with Python 3.

iostream is a pretty core C++ thing. I've no idea about that one!

I'll take a look at the deps when I have time. Probably after I've merged it into main. Like everyone else, I don't have too  much time to maintain this package right now. Maybe after the CD's out...
