### ISSUE TITLE
Failed to build.

### ISSUE THREAD

**Issue by toadzroc** [kampfschlaefer/jackmix#24]
Trying to build jackmix, and get this message before the build stops.

$ scons
scons: Reading SConscript files ...
Configuring qt5muc...
Checking if the output of 'moc -v' contains 'moc 5.' (cached) no
Checking if the output of 'moc5 -v' contains 'moc 5.' (cached) no
Checking if the output of 'moc-qt5 -v' contains 'moc 5.' (cached) no

What am i missing here?

MXDE distro, mx 21 version.

**Comment by nickbailey** [comment]
It looks like maybe you don't have the qt5 build stuff installed? Scons tries running various flavours of the metaobject compiler (moc) and looks for the version number. What happens if you try running the moc from the command line? I see something like this:

```
nick@polonius:~/Packages/jackmix$ moc -v
moc 5.15.2

```

**Comment by toadzroc** [comment]
You're right. I was missing the qtbase5-dev-tools dep.
It's built successfully this time.

Thanks for the help.

I'll close this issue.
