### ISSUE TITLE
moc version and scons

### ISSUE THREAD

**Issue by jmeekr** [kampfschlaefer/jackmix#28]
Running `scons` will not build because it cannot find `moc` because of these two lines:

https://github.com/kampfschlaefer/jackmix/blob/master/admin/qt5muc.py#L89
https://github.com/kampfschlaefer/jackmix/blob/master/admin/qt5muc.py#L108

I have `moc-qt5` installed on Fedora.

```bash
moc-qt5 -v
# moc-qt5 5.15.10
```

If I run the `count` in the python interpreter I get this

```python
>>> s
'moc-qt5 5.15.10'
>>> s.count("moc 5.")
0
```
which should be what

```python
 moc = CommandFromList( ( "moc", "moc5", "moc-qt5" ), "moc 5." )
```
is doing.

Setting it to match the other command lists works and compiles.

```python
 moc = CommandFromList( ( "moc", "moc5", "moc-qt5" ), "5." )
```

**Comment by nickbailey** [comment]
Good call. Tested in the dev branch and now merged with master.

I don't know why it wasn't the same as the others with just the "5." but FWIW Debian bookworm's version of moc doesn't print the "-qt5" so I never noticed:

```
jackmix$ moc --version
moc 5.15.8

```
The good thing about standards is there are so many of them :wink: 

Thank you very much for taking the time to report it.
