### ISSUE TITLE
Update Install

### ISSUE THREAD

**Issue by mendomusic** [kampfschlaefer/jackmix#4]
Please update the [INSTALL](https://github.com/kampfschlaefer/jackmix/blob/master/INSTALL) instructions.

Please include the dependency packages:
scons
```
scons: Reading SConscript files ...
Configuring qt5muc...
Checking if the output of 'moc -v' contains 'moc 5.' (cached) no
Checking if the output of 'moc5 -v' contains 'moc 5.' (cached) no
Checking if the output of 'moc-qt5 -v' contains 'moc 5.' (cached) no
```

Thanks.

**Comment by nickbailey** [comment]
Sorry for the very late response, I've not been here for a while.

I suppose you checked out the qt5 branch. Can you run moc from the command line? I can't reproduce this, and `moc -v` gives me `moc 5.11.3`
