### ISSUE TITLE
Make qt5 the default and release a new version

### ISSUE THREAD

**Issue by dvzrv** [kampfschlaefer/jackmix#5]
Title says it all: Please release a new version, where qt5 is the default qt version.
qt4 is mega dead!

Thanks a lot! :)

**Comment by nickbailey** [comment]
The qt5 branch is working for me. Did I hide it or something?

Let us know if the Qt 5 version works for you. So far the silence is deafening. If enough people tell me I've not broken it, Maybe we can make it the default.

**Comment by trebmuh** [comment]
Hi @nickbailey , just to let you know that I've been testing the qt5 branch and it works as expected so far.  That being said, I've not been using the non-qt5 version before so I can't tell if all the features are equal.

I've got a package (still in the testing phase at the time of writing) which is going to hit the users repository of LibraZiK soonish.

Great job!

**Comment by nickbailey** [comment]
On Sunday, 10 March 2019 23:16:47 GMT Olivier Humbert wrote:
> Hi @nickbailey , just to let you know that I've been testing the qt5 branch
> and it works as expected so far. I've not been using the non-qt5 version
> before so I can't tell if all the feature are equal that being said.
> 
> I've got a package (still in the testing phase at the time of writing) which
> is going to hit the users repository of LibraZiK soonish.
> 
> Great job!

Thanks for that, Oliver! Glad to know it's working for you. I only worked on 
it because I needed it (you've probably seen https://vimeo.com/75655401) so 
nice to hear it's made it to the big time :) That's the Qt4 version in the 
video if I remember correctly.

N/.

**Comment by trebmuh** [comment]
Hi, nope, I didn't see this video before, but now, I do!
Thanks for the link.

**Comment by luzpaz** [comment]
Many downstream packaging repos are starting to purge builds that rely on Qt4.  Please consider making qt5 branch default to avoid this

**Comment by dvzrv** [comment]
> The qt5 branch is working for me. Did I hide it or something?

That's great to hear! For packaging purposes it's completely useless to me though, as I'm building releases and not HEAD of a branch. As I'd like to package this for Arch Linux, I can't build the current latest version, as that's qt4 and we've purged qt4 a couple of months ago.

@trebmuh seems to have successfully tested it though. Would be awesome if this could be made the default now to be able to start packaging and further improving it! :)
